name: README build

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
            - name: Install dependencies
              run: npm install
            - name: Generate README file
              run: |
                  coffee -c index.coffee
                  node index.js
                  rm index.js
            - name: Commit and push if it changed
              run: |
                  git config user.name "chen.xing"
                  git config user.email "chenxing.io@outlook.com"
                  git add -A
                  git commit -m "README build" || exit 0
                  git push
